package Stratego;


import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jenniferbueso
 */
public class CrearPlayer extends javax.swing.JFrame {
    ArrayList<UsuariosInfo> listaUsuarios;
    ArrayList<LogsInfo> listaLogs;
    ArrayList<UsuariosEliminadosInfo> listaUsuariosEliminados;
    
    //Atributos por Default de la Cuenta
    private boolean modoTutorial = true;
    
    /**
     * Creates new form CrearPlayer
     */
    public CrearPlayer(ArrayList<UsuariosInfo> listaUsuariosExterna, ArrayList<LogsInfo> listaLogsExterna, ArrayList<UsuariosEliminadosInfo> listaUsuariosEliminadosExterna, boolean ModoJuego) {
        initComponents();
        
        inicializarListaUsuarios(listaUsuariosExterna);
        inicializarListaLogs(listaLogsExterna);
        inicializarListaUsuariosEliminados(listaUsuariosEliminadosExterna);
        
        //Pantalla al Centro
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1180, 626);
        setLocationRelativeTo(null);
        setVisible(true);
        
        //Modo Tutorial por Default
        modoTutorial = ModoJuego;
        
    }

    private void inicializarListaUsuarios(ArrayList<UsuariosInfo> listaUsuariosExterna) {
        listaUsuarios = (listaUsuariosExterna == null) ? new ArrayList<>() : listaUsuariosExterna;
    }
    
    private void inicializarListaLogs(ArrayList<LogsInfo> listaLogsExterna) {
        listaLogs = (listaLogsExterna == null) ? new ArrayList<>() : listaLogsExterna;
    }
    
    private void inicializarListaUsuariosEliminados(ArrayList<UsuariosEliminadosInfo> listaUsuariosEliminadosExterna) {
        listaUsuariosEliminados = (listaUsuariosEliminadosExterna == null) ? new ArrayList<>() : listaUsuariosEliminadosExterna;

        if (listaUsuariosEliminadosExterna == null) {
            listaUsuariosEliminados.add(new UsuariosEliminadosInfo("kris3", "kris3"));
            listaUsuariosEliminados.add(new UsuariosEliminadosInfo("karla05", "12345"));
            listaUsuariosEliminados.add(new UsuariosEliminadosInfo("lopez", "hola5"));
            System.out.println("Usuarios eliminados inicializados.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        BotonCrear = new javax.swing.JLabel();
        BotonCancelar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(0, 0, 0));
        UsernameField.setBorder(null);
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 221, 320, 40));

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        PasswordField.setBorder(null);
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 355, 320, 40));

        BotonCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/BotonCrear.png"))); // NOI18N
        BotonCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCrearMouseClicked(evt);
            }
        });
        jPanel1.add(BotonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 470, 290, 70));

        BotonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/BotonCancelar.png"))); // NOI18N
        BotonCancelar.setText("jLabel1");
        BotonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCancelarMouseClicked(evt);
            }
        });
        jPanel1.add(BotonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 470, 290, 70));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/CrearPlayer(833 x 462 px).png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void BotonCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCancelarMouseClicked
        this.setVisible(false);
        PantallaPrincipal pantallaPrincipal = new PantallaPrincipal(listaUsuarios,this.listaLogs,this.listaUsuariosEliminados,modoTutorial);
        pantallaPrincipal.setVisible(true);
    }//GEN-LAST:event_BotonCancelarMouseClicked

    private void BotonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCrearMouseClicked
        // Verificar si el usuario ya existe
        boolean usuarioExistente = verificarUsuarioExistente(UsernameField.getText());

        if (usuarioExistente) {
            JOptionPane.showMessageDialog(null, "Este usuario ya está registrado.", "Usuario Existente", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Verificar seguridad de la contraseña
            if (PasswordField.getText().length() != 5) {
                JOptionPane.showMessageDialog(null, "La contraseña debe tener exactamente 5 caracteres.", "Error de Contraseña", JOptionPane.WARNING_MESSAGE);
            } else {
                // Crear nuevo usuario y agregarlo a la lista
                String nuevoNombreUsuario = UsernameField.getText();
                String nuevaContraseña = PasswordField.getText();

                UsuariosInfo nuevoUsuario = new UsuariosInfo(nuevoNombreUsuario, nuevaContraseña);
                listaUsuarios.add(nuevoUsuario);
                            
                UsuariosEliminadosInfo nuevoUsuarioEliminar = new UsuariosEliminadosInfo(nuevoNombreUsuario, nuevaContraseña);
                listaUsuariosEliminados.add(nuevoUsuarioEliminar);

                //Mostrar mensaje de inicio de sesión exitoso
                JOptionPane.showMessageDialog(null, "¡Usuario registrado con éxito!", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotonCrearMouseClicked
    
    // Método para verificar si un usuario ya existe en la lista
    private boolean verificarUsuarioExistente(String nombreUsuario) {
        for (UsuariosInfo usuario : listaUsuarios) {
            if (usuario.getUsuarioG().equals(nombreUsuario)) {
                return true;
            }
        }
        return false;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPlayer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPlayer(null,null,null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonCancelar;
    private javax.swing.JLabel BotonCrear;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
