package Stratego;


import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jenniferbueso
 */
public class LogIn extends javax.swing.JFrame {
    ArrayList<UsuariosInfo> listaUsuarios;
    ArrayList<LogsInfo> listaLogs;
    ArrayList<UsuariosEliminadosInfo> listaUsuariosEliminados;
    
    //Atributos para Mostrar en Perfil
    private String usernameMostrar, contraMostrar;
    
    //Atributos por Default de la Cuenta
    private boolean modoTutorial = true;
    
    public LogIn(ArrayList<UsuariosInfo> listaUsuariosExterna, ArrayList<LogsInfo> listaLogsExterna, ArrayList<UsuariosEliminadosInfo> listaUsuariosEliminadosExterna, boolean ModoJuego) {
        
        inicializarListaUsuarios(listaUsuariosExterna);
        inicializarListaLogs(listaLogsExterna);
        inicializarListaUsuariosEliminados(listaUsuariosEliminadosExterna);
        
        //Crear lista si hace falta una
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(1180, 626);
        setLocationRelativeTo(null);
        setVisible(true);
        
        //Modo Tutorial por Default
        modoTutorial = ModoJuego;
        
        //Verificar Lista
        StringBuilder historialUsuariosBuilder = new StringBuilder();
        for (UsuariosEliminadosInfo usuario : listaUsuariosEliminados) {
            historialUsuariosBuilder.append(usuario.getUsuariosEliminado());  // Corregir el método para obtener el usuario eliminado
            historialUsuariosBuilder.append("\n");
        }
        System.out.println(historialUsuariosBuilder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PasswordField = new javax.swing.JPasswordField();
        UsernameField = new javax.swing.JTextField();
        BotonLogIn = new javax.swing.JLabel();
        BotonSignUp = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PasswordField.setBackground(new java.awt.Color(255, 255, 255));
        PasswordField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(0, 0, 0));
        PasswordField.setBorder(null);
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 337, 320, 40));

        UsernameField.setBackground(new java.awt.Color(255, 255, 255));
        UsernameField.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(0, 0, 0));
        UsernameField.setBorder(null);
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 222, 320, 40));

        BotonLogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/LogInInterfaz.png"))); // NOI18N
        BotonLogIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLogInMouseClicked(evt);
            }
        });
        jPanel1.add(BotonLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 410, 310, 70));

        BotonSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/BotonSignUp.png"))); // NOI18N
        BotonSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSignUpMouseClicked(evt);
            }
        });
        jPanel1.add(BotonSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(934, 496, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/BotonRegresarLogIn.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 530, 60, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondosInterfaz/LogIn(833 x 462 px).png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarListaUsuarios(ArrayList<UsuariosInfo> listaUsuariosExterna) {
        listaUsuarios = (listaUsuariosExterna == null) ? new ArrayList<>() : listaUsuariosExterna;
    }
    
    private void inicializarListaLogs(ArrayList<LogsInfo> listaLogsExterna) {
        listaLogs = (listaLogsExterna == null) ? new ArrayList<>() : listaLogsExterna;
    }
    
    private void inicializarListaUsuariosEliminados(ArrayList<UsuariosEliminadosInfo> listaUsuariosEliminadosExterna) {
        listaUsuariosEliminados = (listaUsuariosEliminadosExterna == null) ? new ArrayList<>() : listaUsuariosEliminadosExterna;
    }
    
    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void BotonLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLogInMouseClicked
        int indiceUsuario = -1;
        String nombreUsuario = UsernameField.getText();

        // Buscar el usuario en la lista
        for (int i = 0; i < listaUsuarios.size(); i++) {
            if (listaUsuarios.get(i).getUsuarioG().equals(nombreUsuario)) {
                indiceUsuario = i;
            }
        }

        // Validación de Existencia de Usuario
        if (indiceUsuario != -1) {
            // Verificar la contraseña
            if (listaUsuarios.get(indiceUsuario).getContraG().equals(PasswordField.getText())) {
                // Inicio de Sesión Exitoso
                JOptionPane.showMessageDialog( null, "¡Bienvenido(a) a Stratego, " + nombreUsuario + "!","Inicio de Sesión Exitoso", JOptionPane.INFORMATION_MESSAGE
                );

                // Abrir la Pantalla Principal
                MenuPrincipal menuPrincipal = new MenuPrincipal(listaUsuarios, listaLogs, nombreUsuario,listaUsuariosEliminados, modoTutorial);
                menuPrincipal.setVisible(true);
                this.setVisible(false);
            } else {
                // Contraseña Incorrecta
                JOptionPane.showMessageDialog(null, "La contraseña ingresada es incorrecta. Por favor, inténtelo nuevamente.","Contraseña Incorrecta", JOptionPane.ERROR_MESSAGE
                );
            }
        } else {
            // Usuario No Existente
            JOptionPane.showMessageDialog( null,  "El usuario '" + nombreUsuario + "' no existe. Por favor, regístrese o ingrese un usuario válido.","Usuario no Existe", JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_BotonLogInMouseClicked
    
    private void BotonSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSignUpMouseClicked
        CrearPlayer crearPlayer = new CrearPlayer(listaUsuarios,this.listaLogs,listaUsuariosEliminados,modoTutorial);
        crearPlayer.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonSignUpMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        PantallaPrincipal pantallaPrincipal = new PantallaPrincipal(listaUsuarios, listaLogs, listaUsuariosEliminados, modoTutorial);
        pantallaPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn(null, null,null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BotonLogIn;
    private javax.swing.JLabel BotonSignUp;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
